### PR TITLE
Update react version to support v15.x

### PR DESCRIPTION
**Pull request by justinanastos**
nrako/react-component-resizable#19

### CODE REVIEW

**Comment by justinanastos** [comment]
Easy peasy, merge me :)

**Comment by zekedroid** [comment]
Awesome 👍 And does it work fine with no warnings when on react 15?

**Comment by justinanastos** [comment]
Yes it does @zekedroid !

**Comment by ahutchings** [comment]
+1 We're upgrading to v15 as well and use this component heavily.

**Comment by jayfunk** [comment]
+1 as well.

**Comment by nrako** [comment]
Sorry for the delay, 1.0.0 🎉  is out.

BTW... what happened with npm 3? shrinkwrap is a complete mess in that version... :rage3: I had to go back to node LTS (I've been doing some Swift lately, I didn't follow much  the node world lately)

**Comment by ahutchings** [comment]
NPM 3 tries to install dependencies into a "maximally flat" directory structure - https://docs.npmjs.com/how-npm-works/npm3. That probably changed where object-assign got installed in your tree.

In my opinion you'd be fine removing the shrinkwrap file from this component, since it's recommended for applications to shrinkwrap anyhow.

**Comment by nrako** [comment]
😮 I see... thanks for the link @ahutchings, and you're right I'd probably be fine without the shrinkwrap file.

**Pull request merged**
